Make parse_dateime::parse_datetime::from_str accept relative time
uutils/parse_datetime pull request #33
Opened 2023-08-21 11:24 UTC by philolo1

@tertsdiepraam @sylvestre 

As discussed in https://github.com/uutils/coreutils/pull/5181, this makes  parse_dateime::parse_datetime::from_str accept relative time.

2023-08-21 12:01 UTC, tertsdiepraam commented
I think this is an opportunity to clean up the interface. There's no reason to expose multiple functions with overlapping functionality. The only public items should be:

- A `parse_datetime` _function_ (module should be private and be renamed)
- A `parse_datetime_at_date` function
- `ParseDateTimeError` (renamed from `ParseDurationError`)

The `parse_datetime` module could be called `datetime_format` maybe (or some other name).

This would hide functions that we are currently using in coreutils, but those should be forced to change :)

2023-08-21 12:31 UTC, philolo1 commented
That makes sense. I think i can tackle that, but with those changes we
should probably also increase the version number. It might cause quite some
conflict for existing prs.

On Mon, Aug 21, 2023 at 21:01 Terts Diepraam ***@***.***>
wrote:

> I think this is an opportunity to clean up the interface. There's no
> reason to expose multiple functions with overlapping functionality. The
> only public items should be:
>
>    - A parse_datetime *function* (module should be private and be renamed)
>    - A parse_datetime_at_date function
>    - ParseDateTimeError (renamed from ParseDurationError)
>
> The parse_datetime module could be called datetime_format maybe (or some
> other name).
>
> This would hide functions that we are currently using in coreutils, but
> those should be forced to change :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/uutils/parse_datetime/pull/33#issuecomment-1686198822>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP4LZTFKHNL6UZSISZYKBDXWNEZTANCNFSM6AAAAAA3YHMPWE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-21 12:34 UTC, tertsdiepraam commented
> That makes sense. I think i can tackle that

Great! Thanks!

> but with those changes we should probably also increase the version number.

I agree, we'll bump the version number on the next release.

> It might cause quite some conflict for existing prs.

Indeed. It's a bit unfortunate, but the sooner we do this the better in my opinion.

2023-08-22 14:31 UTC, philolo1 commented
@tertsdiepraam I have done some refactoring. When you have some time, can you take a look a look (its quite a big renaming / refactor, so i am sure there will be some revisions).

Here is what i did:
```  
* put the `parse_datetime` into lib.rs
* Create new file `parse_relative_time.rs` with the relative time helper function.
* Renames `from_str` to `parse_datetime` and `parse_relative_time`.
* Adds function `parse_datetime_at_date`
* Update Readme.
* Update version number as interfaces changes
```

2023-08-22 15:15 UTC, tertsdiepraam commented
We'll get to the version number once we actually publish. You can revert that for now.

Also, `edition` in `Cargo.toml` refers to the Rust edition. There's no 2023 edition. 2021 is the latest (and the next one will be 2024). That's what makes the CI fail.

2023-08-22 15:19 UTC, tertsdiepraam reviewed
First little comment. I'll get to the rest once the CI passes. But looks promising!

2023-08-22 15:19 UTC, tertsdiepraam commented on src/lib.rs
> +use std::thread::yield_now;
I don't think this is supposed to be here :)

2023-08-22 15:26 UTC, philolo1 commented
@tertsdiepraam Sure, and thanks for the comments. I will mention you ones the pipeline is fixed.

2023-08-22 15:44 UTC, philolo1 commented
@tertsdiepraam the pipeline is passing now.

2023-08-22 17:27 UTC, sylvestre commented
needs to be rebased :)

2023-08-23 11:11 UTC, philolo1 commented
@sylvestre rebased

2023-08-24 11:41 UTC, philolo1 commented
Any updates/ feedback?

2023-08-24 14:20 UTC, tertsdiepraam commented
It's only been a day. We're not that fast ;p

I'll take a look soon!

2023-08-26 14:54 UTC, tertsdiepraam requested changes
Alright, sorry it took a while. These kinds of changes are always a bit hard to review, because it's hard to distinguish stuff being moved around with actual changes in the code. I might have accidentally commented on some things that aren't due to this change. If that's the case, just reply saying that it's irrelevant :)

2023-08-26 14:54 UTC, tertsdiepraam commented on Cargo.toml
> +description = "parsing human-readable relative and absolute time strings and converting them to a DateTime"
```suggestion
description = "parsing human-readable time strings and converting them to a DateTime"
```
Since the relative/absolute distinction is no longer that important. I'd phrase it like this.

2023-08-26 14:54 UTC, tertsdiepraam commented on README.md
> +
Is this just GitHub being weird or are these lines indented with one space?

2023-08-26 14:54 UTC, tertsdiepraam commented on fuzz/Cargo.lock
Please revert this. We can do updates separately.

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +pub mod parse_relative_time;
Why should this be exposed?

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +use crate::parse_relative_time::parse_relative_time;
```suggestion
use parse_relative_time::parse_relative_time;
```
I think this should be enough, because we're already in the crate root. I might be wrong though.

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +            ParseDateTimeError::InvalidRegex(err) => {
```suggestion
            Self::InvalidRegex(err) => {
```
There was a clippy lint for this in the coreutils repo. Why should probably enable that here too.

Same goes for the other match arm.

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +        ParseDateTimeError::InvalidRegex(err)
```suggestion
        Self::InvalidRegex(err)
```

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +    pub(crate) const ISO_8601: &str = "%Y-%m-%d";
I think they're `pub(crate)` sort of automatically because `format` is not `pub`, so just `pub` should be enough.

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +/// * relative time to now, e.g. "+1 hour"
Maybe it makes more sense to document this in the documentation for the crate itself? I.e. with `//!` in the `lib.rs` file. Or we can document it in the README and then include that as the crate docs (as explained here: https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html?highlight=include_str#the-doc-attribute)

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +) -> Result<DateTime<FixedOffset>, ParseDateTimeError> {
It wasn't `AsRef<str>` before. was it? I can't remember, did we discuss this somewhere? I think I might prefer plain and simple `&str`. Why does `Clone` have to be there?

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +) -> Result<DateTime<FixedOffset>, ParseDateTimeError> {
Oh I see that it was `AsRef` already for absolute times. Not your fault then, so not your concern. I might clean that up later.

2023-08-26 14:54 UTC, tertsdiepraam commented on src/lib.rs
> +pub mod parse_relative_time;
Is it because of tests? If so, then that function should be tested as unit tests in the module itself, not in the `tests` folder.

2023-08-27 02:51 UTC, philolo1 commented
@tertsdiepraam thanks for taking the time to review this.

2023-08-28 11:28 UTC, philolo1 commented on src/lib.rs
> +pub mod parse_relative_time;
@tertsdiepraam yeah i think we can move the tests/simple.ts to the relavant files.

2023-08-28 12:08 UTC, philolo1 commented
@tertsdiepraam i believe i have adjusted the code according to your review. As its a big change of the library, take your time to review it.

2023-08-28 15:37 UTC, tertsdiepraam reviewed
Nice! This is almost ready to be merged, just some small final things to clean up.

2023-08-28 15:37 UTC, tertsdiepraam commented on fuzz/Cargo.lock
This one seems to reappeared :)

2023-08-28 15:37 UTC, tertsdiepraam commented on fuzz/Cargo.toml
> +version = "0.2.0"
We don't publish the fuzz crates, so I think it's fine to just leave these at `0.1.0`.

2023-08-28 15:37 UTC, tertsdiepraam commented on src/lib.rs
> +        ParseDateTimeError::InvalidRegex(err)
You resolved this but it wasn't fixed. Do you think this is not necessary?

2023-08-29 00:03 UTC, philolo1 commented on src/lib.rs
> +        ParseDateTimeError::InvalidRegex(err)
@tertsdiepraam i think this was at another place, i missed that, thanks.

2023-08-29 00:16 UTC, philolo1 commented
@tertsdiepraam i believe i fixed all issues.

2023-08-29 08:06 UTC, merged

2023-09-23 07:54 UTC, sylvestre commented
@philolo1 is it by design that parse_relative_time is private?
I am trying to use it in the rust coreutils:

```
error[E0603]: function `parse_relative_time` is private
  --> src/uu/touch/src/touch.rs:92:49
   |
92 |             if let Ok(offset) = parse_datetime::parse_relative_time(date) {
   |                                                 ^^^^^^^^^^^^^^^^^^^ private function
```

2023-09-23 08:15 UTC, philolo1 commented
@sylvestre i am sorry I do not remember why we only exposed one function. I dont see any issue also exposing this function. 
Do you remember the reason @tertsdiepraam ?
@sylvestre it would be fine with me to expose this.

2023-09-23 08:25 UTC, sylvestre commented
@philolo1 yeah, it is significantly reducing the scope of this crate :)

could you please make the change? thanks

2023-09-23 08:30 UTC, philolo1 commented
Sure i can do it either today or tomorrow @sylvestre , then we should create a new version

2023-09-23 08:40 UTC, sylvestre commented
actually, i did it here :)
https://github.com/uutils/parse_datetime/pull/50

2023-09-23 08:54 UTC, philolo1 commented
Thanks

On Sat, Sep 23, 2023 at 17:41 Sylvestre Ledru ***@***.***>
wrote:

> actually, i did it here :)
> #50 <https://github.com/uutils/parse_datetime/pull/50>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/uutils/parse_datetime/pull/33#issuecomment-1732256148>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP4LZTN6DPSMFCAIRAQVKLX32OB7ANCNFSM6AAAAAA3YHMPWE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-23 10:46 UTC, tertsdiepraam commented
> Do you remember the reason @tertsdiepraam ?

Yes, there's a good reason not to do relative time only, because a relative time on its own is undefined. For example, if we get back a relative time of 1 month, how many days should we go forward? We've tried to work around this a bit, but that makes it more difficult. Instead we should always parse the full datetime relative to some reference datetime (which is the current time by default). So, in that format both "tomorrow" and "2023-09-23" are supported. I don't think there's anything in the coreutils that accept only a relative time, but not an absolute time as well.

2023-09-23 15:31 UTC, sylvestre commented
oh ok, my bad :)