Support weekdays in parse_datetime
uutils/parse_datetime pull request #34
Opened 2023-08-23 01:53 UTC by philolo1

@tertsdiepraam @cakebaker @sylvestre 
This commit resolves issue #23.

Adds parse_weekday function that uses chrono weekday parser with a map for edge cases. Adds tests cases to make sure it works correctly.

2023-08-23 07:33 UTC, philolo1 commented
@tertsdiepraam can you link to that pr?

2023-08-24 11:43 UTC, philolo1 commented
So should i wait for https://github.com/uutils/parse_datetime/pull/25 to be merged and then refactor?

2023-08-24 14:16 UTC, tertsdiepraam commented
Hmm yeah I'm not really sure what the best course of action is. The situation is a bit unfortunate. I guess it depends on a few things:

- Will #25 be ready soon?
- How relevant is this PR to #25, i.e. can we reuse significant parts of this with `nom`?

The first question is kinda tough. I think a basic `nom` version of this library _should_ be merged soon, just to get the transition going. Which might not be the entirety of #25. The second question is interesting. At the least the tests are relevant after the introduction of `nom`.

Maybe another approach is to transition to `nom` from the bottom up. What I mean with that is that we port small parts first and gradually build up to parsing the whole thing with `nom`. For example, if we make a `nom`-based` function to parse weekdays, we can easily integrate that later.

I'm really just explaining my thoughts here. I'm not yet really sure what the best approach is. What do you think?

2023-08-24 14:50 UTC, philolo1 commented
> Hmm yeah I'm not really sure what the best course of action is. The situation is a bit unfortunate. I guess it depends on a few things:
> 
> * Will [Make a beginning of parsing GNU date `items` with nom #25](https://github.com/uutils/parse_datetime/pull/25) be ready soon?
> * How relevant is this PR to [Make a beginning of parsing GNU date `items` with nom #25](https://github.com/uutils/parse_datetime/pull/25), i.e. can we reuse significant parts of this with `nom`?
> 
> The first question is kinda tough. I think a basic `nom` version of this library _should_ be merged soon, just to get the transition going. Which might not be the entirety of #25. The second question is interesting. At the least the tests are relevant after the introduction of `nom`.
> 
> Maybe another approach is to transition to `nom` from the bottom up. What I mean with that is that we port small parts first and gradually build up to parsing the whole thing with `nom`. For example, if we make a `nom`-based` function to parse weekdays, we can easily integrate that later.
> 
> I'm really just explaining my thoughts here. I'm not yet really sure what the best approach is. What do you think?

How about waiting until next week and see the progress of #25. If nothing happens i can rewrite this pr first to use nom and check the pr.

2023-08-29 13:04 UTC, tertsdiepraam commented on src/lib.rs
> +        let now = Local::now().naive_local();
I think we shouldn't use `now` here, but the reference `date`. Also I think we don't need to convert a naive date, which should simplify the code a bit.

2023-08-29 13:04 UTC, tertsdiepraam commented on .gitignore
> +fuzz/corpus
I think this was fixed in your other PR, but in a `.gitignore` in the `fuzz` directory.

2023-08-29 13:11 UTC, philolo1 commented on src/parse_weekday.rs
> +    [("tues", "tue"), ("thurs", "thu"), ("thus", "thu")];
@tertsdiepraam its "thurs"

2023-08-29 13:11 UTC, philolo1 commented
@tertsdiepraam thanks for reviewing, but i am currently rewriting it to use nom.

2023-08-29 13:13 UTC, philolo1 commented
I converted it to draft, sorry.

2023-08-29 13:14 UTC, philolo1 commented on src/parse_weekday.rs
> +    [("tues", "tue"), ("thurs", "thu"), ("thus", "thu")];
oh sorry i think i did this by mistake, good catch

2023-08-29 14:22 UTC, philolo1 commented
@tertsdiepraam it should be ready to review now.

2023-08-29 19:13 UTC, tertsdiepraam requested changes
Interesting! I quite like how that's looking. It's definitely a nice way to start using `nom`!

2023-08-29 19:13 UTC, tertsdiepraam commented on src/lib.rs
> +            .unwrap();
Can't we use `date` directly? Also by using `Local` directly we might get into trouble if we change `date` to not (necessarily) use `Local` as timezone.

2023-08-29 19:13 UTC, tertsdiepraam commented on src/lib.rs
> +        }
You've written your own `while` loop :)
```suggestion
        while beginning_of_day.weekday() != weekday {
            beginning_of_day += Duration::days(1);
        }
```

2023-08-29 19:13 UTC, tertsdiepraam commented on src/parse_weekday.rs
> +        for day in days.iter() {
I _think_ `iter` is redundant here.

2023-08-29 19:13 UTC, tertsdiepraam commented on src/parse_weekday.rs
> +                assert_eq!(parse_weekday(str).unwrap(), day.1);
```suggestion
                assert_eq!(parse_weekday(str), Ok(day.1));
```

2023-08-29 19:13 UTC, tertsdiepraam commented on src/parse_weekday.rs
> +            test_strings.push(format!("{}{}", left.to_lowercase(), right.to_uppercase()));
I'd love it if we can simplify this, because technically this is just a bunch `assert_eq!`s. I think tests are perfectly fine if they are repetitive and should contain as little additional logic as possible.

It could be something like:
```rust
for (string, day) in days {
    assert_eq!(parse_weekday(string), Ok(day));
    assert_eq!(parse_weekday(format!("  {string}"), Ok(day));
    // etc.
}
```

2023-08-29 23:25 UTC, philolo1 commented on src/parse_weekday.rs
> +        }),
@tertsdiepraam I am not sure what "m" means, but it does not seem to be monday.

This is what my ubuntu puts out :
```
ubuntu@ip-172-31-46-7:~$ date -d 'm'
Tue Aug 29 21:00:00 JST 2023
```

2023-08-30 02:09 UTC, philolo1 commented
@tertsdiepraam i did all the requests accept one, i am not sure what "m" means, but it does not seem to be monday. 

I just tested all letters from a to z with `date` and this is the result:

```
a
Wed Aug 30 08:00:00 JST 2023
b
Wed Aug 30 07:00:00 JST 2023
c
Wed Aug 30 06:00:00 JST 2023
d
Wed Aug 30 05:00:00 JST 2023
e
Wed Aug 30 04:00:00 JST 2023
f
Wed Aug 30 03:00:00 JST 2023
g
Wed Aug 30 02:00:00 JST 2023
h
Wed Aug 30 01:00:00 JST 2023
i
Wed Aug 30 00:00:00 JST 2023
j
date: invalid date ‘j’
k
Tue Aug 29 23:00:00 JST 2023
l
Tue Aug 29 22:00:00 JST 2023
m
Tue Aug 29 21:00:00 JST 2023
n
Wed Aug 30 10:00:00 JST 2023
o
Wed Aug 30 11:00:00 JST 2023
p
Wed Aug 30 12:00:00 JST 2023
q
Wed Aug 30 13:00:00 JST 2023
r
Wed Aug 30 14:00:00 JST 2023
s
Wed Aug 30 15:00:00 JST 2023
t
Wed Aug 30 16:00:00 JST 2023
u
Wed Aug 30 17:00:00 JST 2023
v
Wed Aug 30 18:00:00 JST 2023
w
Wed Aug 30 19:00:00 JST 2023
x
Wed Aug 30 20:00:00 JST 2023
y
Wed Aug 30 21:00:00 JST 2023
z
Wed Aug 30 09:00:00 JST 2023
```

2023-08-30 02:21 UTC, philolo1 commented
@tertsdiepraam i believe i found the reference source code, apparently "WEDNES" is also valid. https://github.com/coreutils/gnulib/blob/master/lib/parse-datetime.y#L1032

2023-08-30 02:30 UTC, philolo1 commented
@tertsdiepraam apparently one letter is military time table, i will create another issue. 

https://github.com/coreutils/gnulib/blob/master/lib/parse-datetime.y#L1155

2023-08-30 02:37 UTC, philolo1 commented
Here is the issue: #39

2023-08-30 05:41 UTC, tertsdiepraam commented on src/parse_weekday.rs
> +        }),
Ah you're right. It's indeed military time zones. Thanks for figuring that out!

2023-08-30 06:17 UTC, tertsdiepraam reviewed
Nice work! I have just two more comments for things that should not be fixed in this PR and one question.

2023-08-30 06:27 UTC, philolo1 commented on src/lib.rs
> +        let mut beginning_of_day = date
i dit not find anything either :(

2023-08-30 06:28 UTC, philolo1 commented on src/lib.rs
> +            let date = Local.with_ymd_and_hms(2023, 02, 28, 10, 12, 3).unwrap();
I am not sure how to best not use local but agreed.

2023-08-30 06:39 UTC, tertsdiepraam commented on src/lib.rs
> +            let date = Local.with_ymd_and_hms(2023, 02, 28, 10, 12, 3).unwrap();
Yeah, `parse_datetime_at_date` should just be generic over the timezone. And then it can be called with `Utc`, `Local` or `FixedOffset`. Like I said though, definitely out of scope for this PR.

2023-08-30 06:47 UTC, philolo1 commented on src/lib.rs
> +        if let Ok(dt) = naive_dt_to_fixed_offset(date, beginning_of_day.naive_local()) {
@tertsdiepraam seems it works, thanks.

2023-08-30 06:49 UTC, philolo1 commented
@tertsdiepraam Thank for the review. I am trying to improve my rust coding skills and contributing to open source is a good opportunity.

2023-08-31 08:59 UTC, philolo1 commented
@tertsdiepraam I am not to familiar with github, it still shows changed requested. Do i have to do something to request review. Furthermore, should i squash the commits or would you do that when you merge it?

2023-09-01 05:00 UTC, philolo1 commented
I squashed, would be nice if someone can get this merged.

2023-09-01 07:45 UTC, sylvestre commented on src/parse_weekday.rs
> +use chrono::Weekday;
please add the license header

2023-09-01 07:55 UTC, sylvestre commented on src/parse_weekday.rs
> +        Err(_) => None,
why don't you return a Result ?
here, it would be 
        Err(_) => Err("Failed to parse weekday"),

2023-09-01 07:58 UTC, philolo1 commented on src/parse_weekday.rs
> +        Err(_) => None,
I had this discussion with @tertsdiepraam, but I think the reason is this is used in `parse_datetime` and we only care about whether it was parsed or not.

2023-09-01 08:01 UTC, philolo1 commented on src/parse_weekday.rs
> +use chrono::Weekday;
done

2023-09-01 08:59 UTC, tertsdiepraam commented on src/parse_weekday.rs
> +        Err(_) => None,
My reasoning was that we only care about the parsing the whole datetime. If a weekday fails, another type of item might still succeedsl.

2023-09-04 07:06 UTC, philolo1 commented on src/parse_weekday.rs
> +        Err(_) => None,
@sylvestre should i change it to Result

2023-09-15 08:52 UTC, philolo1 commented on src/parse_weekday.rs
> +        Err(_) => None,
@tertsdiepraam @sylvestre its been a while, i am fine with whatever but it would be good to get this pr also merged, before we forget what it was about :) .

2023-09-15 09:08 UTC, sylvestre reviewed
sorry, i didn't submitted my comments :(

2023-09-19 08:49 UTC, philolo1 commented on src/parse_weekday.rs
> +        value(Weekday::Mon, alt((tag("monday"), tag("mon")))),
@sylvestre done

2023-09-19 09:44 UTC, merged

2023-09-19 09:44 UTC, sylvestre commented
thanks